# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-25 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_auto_20191125_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='player_history',
        ),
        migrations.AlterField(
            model_name='player',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Player'),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='Team'),
        ),
    ]
