# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-26 09:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_auto_20191125_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contestant1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_winner_contestant1', to='team.Team')),
                ('contestant2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_winner_contestant2', to='team.Team')),
            ],
        ),
    ]
