# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-26 11:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_matches'),
    ]

    operations = [
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner', models.CharField(blank=True, max_length=100, null=True)),
                ('contestant1_points', models.CharField(blank=True, max_length=100, null=True)),
                ('contestant2_points', models.CharField(blank=True, max_length=100, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Matches')),
            ],
        ),
    ]
